Sync to v2.3
amun/CMTAT-Foundry pull request #1
Opened 2023-11-08 10:18 UTC by diego-G

2024-01-08 20:37 UTC, zarifpour requested changes

2024-01-08 20:37 UTC, zarifpour commented on README.md
> +The CMTAT contracts are included as a [submodule](CMTAT/) of the present repository. The current version used is the version [2.3]([https://github.com/CMTA/CMTAT/releases/tag/2.3-Beta](https://github
There is an issue with the hyperlink here.

```suggestion
The CMTAT contracts are included as a [submodule](CMTAT/) of the present repository. The current version used is the version [2.3](https://github.com/CMTA/CMTAT/releases/tag/v2.3.0).
```

2024-01-08 20:37 UTC, zarifpour commented on README.md
> +> The majority of tests provided are not updated and are incomplete.
```suggestion
> [!Warning]
> This repository is still under development.
> The majority of tests provided are not updated and are incomplete.
```
> [!Warning]
> This repository is still under development.
> The majority of tests provided are not updated and are incomplete.

OR

> [!Caution]
> This repository is still under development.
> The majority of tests provided are not updated and are incomplete.

2024-01-08 20:37 UTC, zarifpour commented on test/ValidationModule/RuleEngineSet.t.sol
> +             IRuleEngine(address(0)),
extra space

2024-01-08 20:37 UTC, zarifpour commented on test/ValidationModule/CodeListInternal.sol
> +abstract contract CodeListInternal {
Should we keep the name `CodeList` and move it into its own director `ValidationModule/Internal`?

2024-01-08 20:37 UTC, zarifpour commented on test/ValidationModule/CodeListInternal.sol
extra space

2024-01-08 20:37 UTC, zarifpour commented on test/BurnModule.t.sol
> +        //emit Burn(ADDRESS1, 20);
Should this be done before merging?

2024-01-08 20:37 UTC, zarifpour commented on test/BurnModule.t.sol
Extra space

2024-01-08 20:37 UTC, zarifpour commented on test/BurnModule.t.sol
> +        */
Should this be done before merging?

2024-01-08 20:37 UTC, zarifpour commented on test/BurnModule.t.sol
> +        */
Should this be done before merging?

2024-01-08 20:37 UTC, zarifpour commented on test/PauseModule.t.sol
>          // Assert
space

2024-01-08 20:37 UTC, zarifpour commented on test/PauseModule.t.sol
> +        vm.expectRevert(bytes("CMTAT: transfer rejected by validation module"));
We can make this message into a variable since it is reused.

2024-01-08 20:37 UTC, zarifpour commented on test/MintModule.t.sol
>          // Arrange - Assert
space

2024-01-08 20:37 UTC, zarifpour commented on test/HelperContract.sol
> +import "CMTAT/mocks/RuleEngine/interfaces/IRuleEngine.sol";
Are these intentionally unused (excluding CMTAT_STANDALONE)?

2024-01-08 20:37 UTC, zarifpour commented on test/HelperContract.sol
> +    //address constant ADMIN_ADDRESS = address(5);
- Should we set the `DEFAULT_ADMIN_ADDRESS` to 5?
- Let's remove the comment?

2024-01-08 20:37 UTC, zarifpour commented on test/EnforcementModule.sol
>          // Assert
space

2024-01-08 20:37 UTC, zarifpour commented on test/EnforcementModule.sol
> +        */
comment?

2024-01-08 20:37 UTC, zarifpour commented on test/EnforcementModule.sol
> +        // TODO: add reason argument
Should we resolve these TODOs before merging?

2024-01-10 14:32 UTC, mariogutval requested changes
Only minor comments. In general, review the use of `prank` vs. the combination of `startPrank` and `stopPrank` to avoid repetition.

2024-01-10 14:32 UTC, mariogutval commented on test/HelperContract.sol
> +import "CMTAT/mocks/RuleEngine/interfaces/IRuleEngine.sol";
I think we can remove it

2024-01-10 14:32 UTC, mariogutval commented on test/ValidationModule/RuleEngineTransfer.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` cheatcodes instead?

2024-01-10 14:32 UTC, mariogutval commented on test/AuthorizationModule.t.sol
> +
```suggestion
```

2024-01-10 14:32 UTC, mariogutval commented on test/BaseModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/EnforcementModule.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/MintModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/MintModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/PauseModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/PauseModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-01-10 14:32 UTC, mariogutval commented on test/PauseModule.t.sol
> +        vm.prank(DEFAULT_ADMIN_ADDRESS);
We can use `startPrank` and `stopPrank` here too.

2024-03-21 16:34 UTC, closed without merging